# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-27 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='image_path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
