# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-27 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0002_size_image_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='Kitten_image',
        ),
    ]
