# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-27 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0003_auto_20161227_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten_image',
            name='image_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
