# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-27 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0004_kitten_image_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitten_image',
            name='image_path',
        ),
    ]
